background: url(https://cdn.jsdelivr.net/gh/sineava/picture-bed/cover/bg-01.jpg)
# 插入代码
inject:
  head:
    - <link rel="stylesheet" href="/css/clock.css"/>
    - <link rel="stylesheet" href="/css/custom.css" media="defer" onload="this.media='all'" />
  bottom:
    # 控制台打印消息
    # - <script async rel="prefetch" src="/js/console.js"></script>
    # 站点公祭日自动变灰判定
    - <script async src="/js/grayscale.js"></script>
    # 浮动动画特效
    # - <script async data-pjax src="/js/floatpanel.js"></script>
    # aplayer音乐
    - <div class="aplayer no-destroy" data-id="1708664797" data-server="tencent" data-type="playlist"   data-order="list" data-fixed="true" data-preload="auto" data-autoplay="false" data-mutex="true" ></div>

menu:
  首页: / || fas fa-home || faa-tada
  时间轴: /archives/ || fas fa-archive
  书籍: /book/ || fas fa-heart
  简历: /interview/ || fas fa-music
  追番: /bangumis/ || icon-bilibili || faa-tada

aplayerInject:
  enable: true
  per_page: true

electric_clock:
  enable: true # 开关
  priority: 8 #过滤器优先权
  enable_page: all # 应用页面
  exclude:
    # - /posts/
    # - /about/
  layout: # 挂载容器类型
    type: class
    name: sticky_layout
    index: 0
  loading: https://cdn.cbd.int/hexo-butterfly-clock/lib/loading.gif #加载动画自定义
  # clock_css: https://cdn.cbd.int/anzhiyu-blog@latest/css/clock.min.css
  clock_css: /css/clock.css
  clock_js: /js/clock.js
  # clock_js: https://cdn.cbd.int/anzhiyu-blog/js/clock.min.js
  # clock_js: https://cdn.cbd.int/hexo-butterfly-clock/lib/clock.min.js
  ip_api: https://widget.qweather.net/simple/static/js/he-simple-common.js?v=2.0

social:
  Github: https://github.com/sineava || icon-gitHub || faa-tada
  Email: https://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=1690150504@qq.com || icon-youxiang || faa-tada
  BiliBili: https://space.bilibili.com/490196005 || icon-bilibili || faa-tada
  RSS: atom.xml || icon-rss || faa-tada
  # QQ: tencent://Message/?Uin=2268025923&amp;websiteName=local.edu.com:8888=&amp;Menu=yes || icon-QQ1 || f
  
comments:
  use:
    - Twikoo

avatar:
  img: 'https://cdn.jsdelivr.net/gh/sineava/picture-bed/common/avatar.png'
  effect: false

# Sponsor/reward
reward:
  enable: true
  coinAudio: https://cdn.cbd.int/akilar-candyassets@1.0.36/audio/coin.mp3
  QR_code:
    - img: https://cdn.jsdelivr.net/gh/sineava/picture-bed/img/wechat.png
      link: 
      text: 微信

CDN:
  option:
    coin_js: /js/coin.js
    coin_css: /css/coin.css

pjax:
  enable: true

footer_beautify:
  enable:
    timer: true # 计时器开关
    bdage: true # 徽标开关
  priority: 5 #过滤器优先权
  enable_page: all # 应用页面
  exclude:
    # - /posts/
    # - /about/
  layout: # 挂载容器类型
    type: id
    name: footer-wrap
    index: 0
  # 计时器部分配置项
  runtime_js: /js/runtime.js
  runtime_css: /css/runtime.css
  # 徽标部分配置项
  swiperpara: 0 #若非0，则开启轮播功能，每行徽标个数
  bdageitem:
    - link: https://hexo.io/ #徽标指向网站链接
      shields: https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo #徽标API
      message: 博客框架为Hexo_v5.4.0 #徽标提示语
    - link: https://butterfly.js.org/
      shields: https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender
      message: 主题版本Butterfly_v3.8.2
    - link: http://creativecommons.org/licenses/by-nc-sa/4.0/
      shields: https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&logo=Claris
      message: 本站采用知识共享署名-非商业性使用-相同方式共享4.0国际许可协议进行许可