background: url(/img/background.jpg)
# 插入代码
inject:
  head:
    - <link rel="stylesheet" href="/css/clock.css"/>
    - <link rel="stylesheet" href="/css/custom.css" media="defer" onload="this.media='all'" />
  bottom:
    # 控制台打印消息
    # - <script async rel="prefetch" src="/js/console.js"></script>
    # 标题卖萌
    - <script async src="/js/diytitle.js"></script>
    # 站点公祭日自动变灰判定
    - <script async src="/js/grayscale.js"></script>
    # 浮动动画特效
    # - <script async data-pjax src="/js/floatpanel.js"></script>
    # aplayer音乐
    - <div class="aplayer no-destroy" data-id="1708664797" data-server="tencent" data-type="playlist"   data-order="list" data-fixed="true" data-preload="auto" data-autoplay="false" data-mutex="true" ></div>

menu:
  首页: / || fas fa-home || faa-tada
  时间轴: /archives/ || fas fa-archive
  追番: /bangumis/ || icon-bilibili1

aplayerInject:
  enable: true
  per_page: true

electric_clock:
  enable: true # 开关
  priority: 8 #过滤器优先权
  enable_page: all # 应用页面
  exclude:
    # - /posts/
    # - /about/
  layout: # 挂载容器类型
    type: class
    name: sticky_layout
    index: 0
  loading: https://cdn.cbd.int/hexo-butterfly-clock/lib/loading.gif #加载动画自定义
  # clock_css: https://cdn.cbd.int/anzhiyu-blog@latest/css/clock.min.css
  clock_css: /css/clock.css
  clock_js: /js/clock.js
  # clock_js: https://cdn.cbd.int/anzhiyu-blog/js/clock.min.js
  # clock_js: https://cdn.cbd.int/hexo-butterfly-clock/lib/clock.min.js
  ip_api: https://widget.qweather.net/simple/static/js/he-simple-common.js?v=2.0

social:
  Github: https://github.com/sineava || icon-gitHub || faa-tada
  Email: https://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=1690150504@qq.com || icon-youxiang || faa-tada
  # BiliBili: https://space.bilibili.com/372204786 || icon-bilibili || faa-tada
  # QQ: tencent://Message/?Uin=2268025923&amp;websiteName=local.edu.com:8888=&amp;Menu=yes || icon-QQ1 || f
  
# comments:
#   use:
#     - Twikoo

avatar:
  img: 'https://cdn.jsdelivr.net/npm/file-assets@1.0.1/img/avatar.jpg'

# Sponsor/reward
  reward:
    enable: true
    coinAudio: https://cdn.cbd.int/akilar-candyassets@1.0.36/audio/coin.mp3
    QR_code:
  CDN:
    # main
    main_css: /css/index.css
    jquery: https://cdn.cbd.int/jquery@latest/dist/jquery.min.js
    main: /js/main.js
    utils: /js/utils.js

pjax:
  enable: true